"""Helpers for golden billing regression tests.

Scenarios are stored as JSON under ``tests/fixtures/golden/scenarios/``.
Each scenario defines the tariff, load/solar pattern, export rate, and
NEM-regime settings declaratively so tariff construction is the same in
tests and during the (future) Monte-Carlo harness.

Expected outputs live at ``tests/fixtures/golden/expected/<name>.json`` and
are regenerated by running pytest with ``PV_SIM_REGEN_GOLDEN=1`` set.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from modules.tariff import TariffSchedule

FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "golden"
SCENARIO_DIR = FIXTURE_ROOT / "scenarios"
EXPECTED_DIR = FIXTURE_ROOT / "expected"


# ---------------------------------------------------------------------------
# Scenario loading
# ---------------------------------------------------------------------------
def list_scenarios() -> list[str]:
    return sorted(p.stem for p in SCENARIO_DIR.glob("*.json"))


def load_scenario(name: str) -> dict[str, Any]:
    path = SCENARIO_DIR / f"{name}.json"
    with path.open() as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Deterministic inputs
# ---------------------------------------------------------------------------
def _dt_index(year: int = 2025) -> pd.DatetimeIndex:
    return pd.date_range(start=f"{year}-01-01", periods=8760, freq="h")


def build_load(pattern: dict[str, Any], year: int = 2025) -> pd.Series:
    """Build a deterministic 8760 load series from a declarative pattern.

    Patterns supported:
      - {"kind": "flat", "value": 50.0}
      - {"kind": "diurnal", "base": 20.0, "peak": 80.0, "peak_hours": [13, 14, 15, 16, 17, 18]}
      - {"kind": "seed", "mean": 40.0, "std": 10.0, "seed": 42}
    """
    idx = _dt_index(year)
    kind = pattern["kind"]
    if kind == "flat":
        values = np.full(8760, float(pattern["value"]))
    elif kind == "diurnal":
        base = float(pattern["base"])
        peak = float(pattern["peak"])
        peak_hours = set(pattern["peak_hours"])
        hours = idx.hour.to_numpy()
        values = np.where(np.isin(hours, list(peak_hours)), peak, base).astype(float)
    elif kind == "seed":
        rng = np.random.default_rng(int(pattern["seed"]))
        values = np.clip(
            rng.normal(float(pattern["mean"]), float(pattern["std"]), 8760),
            0.0,
            None,
        )
    else:
        raise ValueError(f"Unknown load pattern kind: {kind}")
    return pd.Series(values, index=idx, name="load_kwh")


def build_solar(pattern: dict[str, Any], year: int = 2025) -> pd.Series:
    """Solar patterns — peaks 10am-3pm, zero at night.

    Supported:
      - {"kind": "bell", "peak": 60.0}
      - {"kind": "zero"}
    """
    idx = _dt_index(year)
    kind = pattern["kind"]
    if kind == "zero":
        values = np.zeros(8760)
    elif kind == "bell":
        peak = float(pattern["peak"])
        hours = idx.hour.to_numpy()
        # smooth daytime bell: cos^2 centered at 12:30, zero before 6 / after 19
        within = (hours >= 6) & (hours <= 19)
        phase = np.where(within, (hours - 12.5) / 6.5, 2.0)
        values = np.where(within, peak * np.maximum(0.0, np.cos(phase * np.pi / 2) ** 2), 0.0)
    else:
        raise ValueError(f"Unknown solar pattern kind: {kind}")
    return pd.Series(values, index=idx, name="solar_kwh")


def build_export_rate(pattern: dict[str, Any], year: int = 2025) -> pd.Series:
    idx = _dt_index(year)
    kind = pattern["kind"]
    if kind == "flat":
        values = np.full(8760, float(pattern["value"]))
    elif kind == "zero":
        values = np.zeros(8760)
    else:
        raise ValueError(f"Unknown export pattern kind: {kind}")
    return pd.Series(values, index=idx, name="export_rate")


# ---------------------------------------------------------------------------
# Tariff construction
# ---------------------------------------------------------------------------
def build_tariff(spec: dict[str, Any]) -> TariffSchedule:
    """Build a TariffSchedule from a scenario spec.

    Supports flat and TOU (two-period: peak hours + off-peak).
    """
    kind = spec["kind"]
    fixed = float(spec.get("fixed_monthly", 0.0))
    minimum = float(spec.get("min_monthly", 0.0))
    if kind == "flat":
        rate = float(spec["rate"])
        energy = [[{
            "rate": rate, "adj": 0.0, "max": None, "unit": "kWh", "effective_rate": rate,
        }]]
        schedule = [[0] * 24 for _ in range(12)]
    elif kind == "tou":
        peak = float(spec["peak_rate"])
        offpeak = float(spec["offpeak_rate"])
        peak_hours = set(spec["peak_hours"])
        energy = [
            [{"rate": peak, "adj": 0.0, "max": None, "unit": "kWh", "effective_rate": peak}],
            [{"rate": offpeak, "adj": 0.0, "max": None, "unit": "kWh", "effective_rate": offpeak}],
        ]
        row = [0 if h in peak_hours else 1 for h in range(24)]
        schedule = [list(row) for _ in range(12)]
    else:
        raise ValueError(f"Unknown tariff kind: {kind}")
    return TariffSchedule(
        label=spec.get("label", f"golden_{kind}"),
        name=spec.get("name", kind.upper()),
        utility=spec.get("utility", "PG&E"),
        fixed_monthly_charge=fixed,
        min_monthly_charge=minimum,
        energy_rate_structure=energy,
        energy_weekday_schedule=schedule,
        energy_weekend_schedule=schedule,
    )


# ---------------------------------------------------------------------------
# Summary extraction
# ---------------------------------------------------------------------------
def summarize_result(result: Any) -> dict[str, Any]:
    """Extract a stable, JSON-serialisable summary from a BillingResult.

    Captures just enough to catch any billing-engine regression without
    coupling to internal DataFrame shapes that may churn.
    """
    m = result.monthly_summary
    monthly_cols = {}
    for col in [
        "net_bill",
        "energy_cost",
        "export_credit",
        "fixed_charge",
        "total_demand_charge",
        "nbc_charge",
    ]:
        if col in m.columns:
            monthly_cols[col] = [round(float(v), 4) for v in m[col].tolist()]

    baseline = getattr(result, "old_rate_annual_baseline", None)
    return {
        "annual_net_bill": round(float(m["net_bill"].sum()), 4) if "net_bill" in m else None,
        "annual_energy_cost": round(float(m["energy_cost"].sum()), 4) if "energy_cost" in m else None,
        "annual_export_credit": round(float(m["export_credit"].sum()), 4) if "export_credit" in m else None,
        "annual_bill_with_solar": round(float(result.annual_bill_with_solar), 4),
        "annual_bill_without_solar": round(float(result.annual_bill_without_solar), 4),
        "annual_savings": round(float(result.annual_savings), 4),
        "old_rate_annual_baseline": round(float(baseline), 4) if baseline is not None else None,
        "monthly": monthly_cols,
    }
